<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <!-- <xacro:macro name="drone_arm" params="num parent_link dis_from_center length diameter arm_incline_angle arm_mesh prop_mesh prop_size_multiplier amass aixx aixy aixz aiyy aiyz aizz rmass rixx rixy rixz riyy riyz rizz angle">  -->
    <xacro:macro name="drone_arm" params="num parent_link dis_from_center length diameter arm_incline_angle arm_mesh prop_mesh prop_size_multiplier rmass rixx rixy rixz riyy riyz rizz angle"> 
        <xacro:property name="core_arm_joint" value="core_arm_joint_${num}" />
        <xacro:property name="arm_link" value="arm_link_${num}" />
        <xacro:property name="rotor_joint" value="rotor_joint_${num}" />
        <xacro:property name="prop_link" value="prop_link_${num}" />
        <xacro:property name="rotor_blade_0" value="rotor_${num}_blade_0" />
        <xacro:property name="rotor_blade_1" value="rotor_${num}_blade_1" />

        <joint name="${core_arm_joint}" type="fixed">
            <parent link="${parent_link}"/>
            <child link="${arm_link}"/>
            <origin xyz="0 0 0" rpy="0 0 ${angle}"/>
        </joint>

        <!-- <xacro:link_creator link_name="${arm_link}" pose_xyz="0 ${cos(arm_incline_angle) * (length / 2.0) + dis_from_center} ${sin(arm_incline_angle) * (length / 2.0)}" pose_rpy="${arm_incline_angle + 1.57079632679} 0 0" mesh_path="${arm_mesh}" scale_xyz="${diameter} ${diameter} ${length}" mass="${amass}" ixx="${aixx}" ixy="${aixy}" ixz="${aixz}" iyy="${aiyy}" iyz="${aiyz}" izz="${aizz}"/> -->
        <xacro:link_creator link_name="${arm_link}" pose_xyz="0 ${cos(arm_incline_angle) * (length / 2.0) + dis_from_center} ${sin(arm_incline_angle) * (length / 2.0)}" pose_rpy="${arm_incline_angle + 1.57079632679} 0 0" mesh_path="${arm_mesh}" scale_xyz="${diameter} ${diameter} ${length}" mass="0.2" ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
        <!-- <xacro:link_creator_no_mass link_name="${arm_link}" pose_xyz="0 ${cos(arm_incline_angle) * (length / 2.0) + dis_from_center} ${sin(arm_incline_angle) * (length / 2.0)}" pose_rpy="${arm_incline_angle + 1.57079632679} 0 0" mesh_path="${arm_mesh}" scale_xyz="${diameter} ${diameter} ${length}"/> -->
        
        <joint name="${rotor_joint}" type="continuous">
            <parent link="${arm_link}"/>
            <child link="${prop_link}"/>
            <origin xyz="0 ${cos(arm_incline_angle) * length + dis_from_center} ${sin(arm_incline_angle) * length}" rpy="${arm_incline_angle} 0 0"/>
            <axis xyz="0 0 1"/>
            <dynamics damping="0.004"/>       
        </joint>
        <gazebo reference="${rotor_joint}">
            <ode>
                <implicit_spring_damper>1</implicit_spring_damper>
            </ode>
        </gazebo>


        <xacro:link_creator link_name="${prop_link}" pose_xyz="0 0 0.03" pose_rpy="0 0 0" mesh_path="${prop_mesh}" scale_xyz="${prop_size_multiplier} ${prop_size_multiplier} ${prop_size_multiplier}" mass="${rmass}" ixx="${rixx}" ixy="${rixy}" ixz="${rixz}" iyy="${riyy}" iyz="${riyz}" izz="${rizz}"/>
        

        <gazebo>
            <plugin name="${rotor_blade_0}" filename="libLiftDragPlugin.so">
                <a0>0.3</a0>
                <alpha_stall>1.4</alpha_stall>
                <cla>4.2500</cla>
                <cda>0.10</cda>
                <cma>0.00</cma>
                <cla_stall>-0.025</cla_stall>
                <cda_stall>0.0</cda_stall>
                <cma_stall>0.0</cma_stall>
                <area>0.002</area>
                <air_density>1.2041</air_density>
                <cp>0.084 0 0</cp>
                <forward>0 -1 0</forward>
                <upward>0 0 1</upward>
                <link_name>${prop_link}</link_name>
            </plugin>

            <plugin name="${rotor_blade_1}" filename="libLiftDragPlugin.so">
                <a0>0.3</a0>
                <alpha_stall>1.4</alpha_stall>
                <cla>4.2500</cla>
                <cda>0.10</cda>
                <cma>0.00</cma>
                <cla_stall>-0.025</cla_stall>
                <cda_stall>0.0</cda_stall>
                <cma_stall>0.0</cma_stall>
                <area>0.002</area>
                <air_density>1.2041</air_density>
                <cp>-0.084 0 0</cp>
                <forward>0 1 0</forward>
                <upward>0 0 1</upward>
                <link_name>${prop_link}</link_name>
            </plugin>
        </gazebo>
    </xacro:macro>




    <xacro:macro name="link_creator" params="link_name pose_xyz pose_rpy mesh_path scale_xyz mass ixx ixy ixz iyy iyz izz">

        <link name="${link_name}">
            <visual>
                <geometry>
                    <mesh filename="${mesh_path}" scale="${scale_xyz}"/>
                </geometry>
                <material name="red">
                    <color rgba="0.8 0.1 0.1 1.0"/>
                </material>
                <origin xyz="${pose_xyz}" rpy="${pose_rpy}"/>
            </visual>

            <collision>
                <geometry>
                    <mesh filename="${mesh_path}" scale="${scale_xyz}"/>
                </geometry>
                <origin xyz="${pose_xyz}" rpy="${pose_rpy}"/>
            </collision>

            <inertial>
                <mass value="${mass}"/>
                <inertia ixx="${ixx}" ixy="${ixy}" ixz="${ixz}" iyy="${iyy}" iyz="${iyz}" izz="${izz}"/>
            </inertial>
        </link>
    </xacro:macro>

    

    <xacro:macro name="link_creator_center_mass" params="link_name pose_xyz pose_rpy mesh_path scale_xyz mass_xyz mass_rpy mass ixx ixy ixz iyy iyz izz">
        <link name="${link_name}">
            <visual>
                <geometry>
                    <mesh filename="${mesh_path}" scale="${scale_xyz}"/>
                </geometry>
                <material name="red">
                    <color rgba="0.8 0.1 0.1 1.0"/>
                </material>
                <origin xyz="${pose_xyz}" rpy="${pose_rpy}"/>
            </visual>

            <collision>
                <geometry>
                    <mesh filename="${mesh_path}" scale="${scale_xyz}"/>
                </geometry>
                <origin xyz="${pose_xyz}" rpy="${pose_rpy}"/>
            </collision>

            <inertial>
                <mass value="${mass}"/>
                <inertia ixx="${ixx}" ixy="${ixy}" ixz="${ixz}" iyy="${iyy}" iyz="${iyz}" izz="${izz}"/>
                <origin xyz="${mass_xyz}" rpy="${mass_rpy}"/>
            </inertial>
        </link>
    </xacro:macro>


    <xacro:macro name="link_creator_no_mass" params="link_name pose_xyz pose_rpy mesh_path scale_xyz">
        <link name="${link_name}">
            <visual>
                <geometry>
                    <mesh filename="${mesh_path}" scale="${scale_xyz}"/>
                </geometry>
                <material name="red">
                    <color rgba="0.8 0.1 0.1 1.0"/>
                </material>
                <origin xyz="${pose_xyz}" rpy="${pose_rpy}"/>
            </visual>

            <collision>
                <geometry>
                    <mesh filename="${mesh_path}" scale="${scale_xyz}"/>
                </geometry>
                <origin xyz="${pose_xyz}" rpy="${pose_rpy}"/>
            </collision>
        </link>
    </xacro:macro>

</robot>



